### ISSUE TITLE
Releases still are not built correctly

### ISSUE THREAD

**Issue by Anthchirp** [GarmanGroup/RADDOSE-3D#11]
Current release (.803) .jar file from Github release page reports version number as:
```
$ java -jar raddose3d.jar -V
Raddose 3D
version 3.0.head
```

Travis build taken from https://dl.bintray.com/garmangroup/RADDOSE-3D/v3.0.803/ correctly reports:
```
$ java -jar raddose3d-803.jar -V
Raddose 3D
version 3.0.803
```

**Comment by Anthchirp** [comment]
I would suggest simply taking the file from travis und using that for releases :)

**Comment by jdickerson95** [comment]
Yes of course, wasn't thinking properly when doing this. Have updated this now.
Cheers.
