### ISSUE TITLE
skin dose in SAXS

### ISSUE THREAD

**Issue by jmholton** [GarmanGroup/RADDOSE-3D#12]
Just did a run of water in a cylindrical quartz capillary. Dose to the "skin" of the sample was low, presumably due to photoelectron escape. However, there should be more photoelectrons coming into the water from the quartz than the other way round, so in reality the skin dose should be higher.  This is a bug, right?

**Comment by jdickerson95** [comment]
Hi James, I've added photoelectron entry from the surrounding into SAXS so it should now be fixed.
