### ISSUE TITLE
maybe get rid of ANTLR

### ISSUE THREAD

**Issue by Anthchirp** [GarmanGroup/RADDOSE-3D#6]
Suspect current parser grammar is broken, leading to ambiguity which allows misidentifying PDB codes as FLOATs (#5). ANTLR was always a bit of a pain - maybe get rid of it?

Will do it if I can find the time over the next 2 weeks. Otherwise I'll forget about it.

**Comment by Anthchirp** [comment]
Realistically no time for this, sorry.

**Comment by jdickerson95** [comment]
I've got this on a list of things to do. Won't get it to it anytime soon but will hopefully get to it eventually
